### ISSUE TITLE
Cannot build pagmo, error at "Linking CXX executable best_solutions_test"

### ISSUE THREAD

**Issue by marcociara379** [esa/pagmo#149]
Hello everyone, I am trying to build PyGMO and i have installed libboost (through apt-get in ubuntu 14.10). The building process stops at
[ 96%] Built target pagmo
[ 96%] Built target pagmo_static
[ 96%] Built target _algorithm
[ 96%] Built target _core
[ 96%] Built target _migration
[ 96%] Built target _problem
[ 96%] Built target _problem_meta
[ 96%] Built target _topology
[ 96%] Built target _util
Linking CXX executable best_solutions_test
 
At this point a huge error appears. It starts with:
../src/libpagmo.a(griewank.cpp.o): In function `boost::archive::detail::oserializer<boost::archive::text_oarchive, pagmo::problem::griewank>::~oserializer()':
griewank.cpp:(.text._ZN5boost7archive6detail11oserializerINS0_13text_oarchiveEN5pagmo7problem8griewankEED2Ev[_ZN5boost7archive6detail11oserializerINS0_13text_oarchiveEN5pagmo7problem8griewankEED5Ev]+0x8): undefined reference to `boost::archive::detail::basic_oserializer::~basic_oserializer()'

and it ends like this:
tests/CMakeFiles/best_solutions_test.dir/build.make:95: recipe for target 'tests/best_solutions_test' failed
make[2]: *** [tests/best_solutions_test] Error 1
CMakeFiles/Makefile2:578: recipe for target 'tests/CMakeFiles/best_solutions_test.dir/all' failed
make[1]: *** [tests/CMakeFiles/best_solutions_test.dir/all] Error 2
Makefile:126: recipe for target 'all' failed
make: *** [all] Error 2

I am running Ubuntu 14.10 64bit and I have Python working.

Thanks in advance.

Marco

**Comment by kiryx** [comment]
Hey Marco,
this is unfortunately an ongoing issue with ubuntu-favored gcc that's been shipped since 13.04 as far as I remember.

The current workarounds are:
1. Change the order of ``pagmo_static`` and ``${MANDATORY_LIBRARIES}`` on line: https://github.com/esa/pagmo/blob/master/CMakeLists.txt#L397 i.e. change it to ``TARGET_LINK_LIBRARIES(main pagmo_static ${MANDATORY_LIBRARIES})``
2. Compile gcc from source and change the ``CMAKE_CXX_COMPILER`` and ``CMAKE_C_COMPILER`` variables in ccmake.

**Comment by marcociara379** [comment]
ok, thank you for your reply, I will try (1) afterwards.

Another thing maybe useful to develpers: I have overrode gcc 4.6 (used by default) with gcc 4.9.


Have a nice day

M
