### ISSUE TITLE
terminate called after throwing an instance of 'std::invalid_argument' what: function: best_idx

### ISSUE THREAD

**Issue by aespielberg** [esa/pagmo#203]
Getting the following error: pagmo 0.4, pygmo 2.4 (but this seems to happen for the most recent version too):

terminate called after throwing an instance of 'std::invalid_argument'
  what():  
function: best_idx
where: /usr/local/include/pagmo/population.hpp, 315
what: Cannot determine the best individual of an empty population

[E 11/24/18 12:36:34.292] Received signal 6 (Aborted)

The weird thing is that this runs fine on my other computer, but not my current one.

Some python code (without my problem definition) for clarity; trying to solve a trajectory optimization problem.  (I can provide more details but don't want to copy-paste a large amount of code here.)  What could be the problem?

```
  uda = ppnf.worhp(screen_output = True, library = "/usr/lib/libworhp.so")


  algo = pg.algorithm(uda)


  udp = RobotProblem(True)
  bounds = udp.get_bounds()
  mean = (np.array(bounds[0]) + np.array(bounds[1])) / 2.0
  num_vars = len(mean)

  prob = pg.problem(udp)
  pop = pg.population(prob, size = 0)   
  
  std = np.ones(len(acts)) * 0.002
  
  x0 = np.random.normal(scale=std, loc=mean, size=(num_vars,))
  
  pop.push_back(x0) #This part is fine and evaluates x0 with no issues.  pop=1 here!!
  
  algo.extract(ppnf.worhp).set_numeric_option("ArmijoMaxAlpha", 0.18)
  algo.extract(ppnf.worhp).set_numeric_option("Timeout", 200000)
  
  pop = algo.evolve(pop)
```

**Comment by darioizzo** [comment]
Sorry for the "late reply" bu we got confused by your message, you claim to be usint pygmo 2.4 and pagmo 0.4 which is weird.
Also this is an issue opened for pagmo 1.x (old and discontinued code). 

Assuming you are using pagmo and pygmo 2.4 (please next time use the pagmo2 project pages to file issues), could you reproduce your problem with another optimizer?

worhp is in the project pagmo_plugins_nonfree and I would like to understand what project your issue is related to.

**Comment by aespielberg** [comment]
I am finally circling back to this issue.  Trying to investigate now.  Would you prefer I move this to the pagmo2 repository?  Sorry for posting in the wrong place.

**Comment by darioizzo** [comment]
yes please move to pagmo2. Will close this on here ...
